AssetMgtSys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("qux.auth.urls")),
    path("", RedirectView.as_view(url="/login/")),
    path("assetmgt/", include("assetmgt.urls")),
]

assetmgt/urls.py
from django.urls import path
from assetmgt.views import *
from . import views

app_name = "assetmgt"
urlpatterns = [
    path("assets/", AssetView.as_view(), name="assetlist"),
    path("assets/add/", AssetCreateView.as_view(), name="add"),
    path("assets/<int:pk>/", AssetUpdateView.as_view(), name="update"),
    path("assets/<int:pk>/delete/", AssetDeleteView.as_view(), name="delete"),
    path("accessories/", AccessoriesView.as_view(), name="accessorylist"),
    path(
        "accessories/detail/<int:pk>/",
        AccessoryDetail.as_view(),
        name="accessorydetail",
    ),
    path("accessories/add/", AccessoryCreateView.as_view(), name="acc_add"),
    path("accessories/<int:pk>/", AccessoryUpdateView.as_view(), name="acc_update"),
    path(
        "accessories/<int:pk>/delete/", AccessoryDeleteView.as_view(), name="acc_delete"
    ),
    path("accassets/<int:pk>/", AccAsset.as_view(), name="acc_asset"),
    path("<int:pk>/", AssetDetail.as_view(), name="assetdetail"),
]

assetmgt/models.py
from django.db import models
from qux.models import CoreModel
from django.urls import reverse
from django.forms import ModelForm
from django.contrib.auth.models import User


class AssetType(CoreModel):
    name = models.CharField(max_length=20, verbose_name="Asset Type")

    def __str__(self):
        return self.name


class AssetModel(CoreModel):
    model_id = models.CharField(max_length=20, verbose_name="Model ID")
    brand_name = models.CharField(max_length=15, verbose_name="Brand")
    type_of_asset = models.ForeignKey(
        AssetType, on_delete=models.DO_NOTHING, verbose_name="Asset Type"
    )
    date_procured = models.DateField(verbose_name="Date Procured")
    price = models.FloatField(verbose_name="Price")
    user = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        null=True,
        default=None,
        blank=True,
        verbose_name="User",
    )
    date_allotted = models.DateField(
        null=True, default=None, verbose_name="Date Allotted", blank=True
    )

    def __str__(self):
        return str(self.id) + self.type_of_asset.name

    def get_absolute_url(self):
        return reverse("assetmgt:assetdetail", kwargs={"pk": self.pk})


class Accessories(CoreModel):
    model_id = models.CharField(max_length=30, verbose_name="Model ID")
    accessory_type = models.CharField(max_length=20, verbose_name="Type")
    asset = models.ForeignKey(
        AssetModel,
        on_delete=models.CASCADE,
        verbose_name="Of Asset",
    )

    def __str__(self):
        return self.accessory_type

    def get_absolute_url(self):
        return reverse("assetmgt:accessorydetail", kwargs={"pk": self.pk})


# class AssetForm(ModelForm):
#     class Meta:
#         model = AssetModel
#         fields = "__all__"

assetmgt/forms.py
from django.forms import ModelForm
from assetmgt.models import Accessories, AssetModel
from django import forms


class AccessoryForm(ModelForm):
    class Meta:
        model = Accessories
        fields = ["model_id", "accessory_type"]


class DateInput(forms.DateInput):
    input_type = "date"


class AssetForm(ModelForm):
    class Meta:
        model = AssetModel
        fields = "__all__"
        widgets = {
            "date_procured": DateInput(),
            "date_allotted": DateInput(),
        }

assetmgt/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import AssetModel, Accessories, AssetType
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AccessoryForm, AssetForm

# view for all assets available can have specific type drop down to pick type to list
class AssetView(ListView):
    model = AssetModel
    template_name = "assetmgt/all_assets.html"

    def get_queryset(self):
        type = self.request.GET.get("type", None)
        if type == None or type == "All":
            queryset = super().get_queryset()
        else:
            queryset = AssetModel.objects.filter(type_of_asset__name=type)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tup = [x.name for x in AssetType.objects.all()]
        context["assettype"] = tup
        return context


# view for specific asset and accessories attached to
class AssetDetail(DetailView):
    model = AssetModel
    template_name = "assetmgt/asset_detail.html"
    # handle selected from the list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fields = AssetModel._meta.fields
        context["fields"] = fields
        context["id"] = kwargs.get("id", None)
        return context

    def get(self, request, *args, **kwargs):
        id = kwargs.get("pk", None)
        querys = Accessories.objects.filter(asset=id)
        context = {}
        assetname = AssetModel.objects.get(pk=id)
        context["object"] = assetname
        context["acc_list"] = querys
        return render(request, self.template_name, context)


class AssetCreateView(CreateView):
    model = AssetModel
    form_class = AssetForm
    template_name = "assetmgt/addasset.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["assetform"] = context.pop("form")
        return context

    def post(self, request, *args, **kwargs):
        if "save_add" in request.POST:
            self.success_url = reverse("assetmgt:add")
        elif "acc_add" in request.POST:
            self.success_url = reverse("assetmgt:acc_add")
        else:
            self.success_url = reverse("assetmgt:assetlist")
        return super().post(request, *args, **kwargs)


class AssetUpdateView(UpdateView):
    model = AssetModel
    form_class = AssetForm
    template_name = "assetmgt/updateasset.html"

    def get_context_data(self, **kwargs):
        id = self.kwargs.get("pk", None)
        querys = Accessories.objects.filter(asset=id)
        kwargs["acc_list"] = querys
        kwargs["id"] = id
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        return reverse("assetmgt:assetlist")


class AssetDeleteView(DeleteView):
    model = AssetModel
    success_url = reverse_lazy("assetmgt:assetlist")
    template_name = "assetmgt/deleteasset.html"

    def get(self, request, *args, **kwargs):
        id = kwargs.get("pk", None)
        querys = Accessories.objects.filter(asset=id)
        context = {}
        assetname = AssetModel.objects.get(pk=id)
        context["object"] = assetname
        context["acc_list"] = querys
        return render(request, self.template_name, context)

    def get_success_url(self):
        return reverse("assetmgt:assetlist")


# Accessories Views


class AccessoriesView(ListView):
    model = Accessories
    template_name = "assetmgt/all_accessories.html"

    def get_queryset(self):
        id = self.request.GET.get("pk", None)
        qs = Accessories.objects.filter(asset=id)
        return qs


class AccessoryDetail(DetailView):
    model = Accessories
    template_name = "assetmgt/asset_detail.html"


class AccessoryCreateView(LoginRequiredMixin, CreateView):
    model = Accessories
    template_name = "assetmgt/addaccessory.html"
    form_class = AccessoryForm
    asset = None

    def form_valid(self, form):
        self.object = form.save(False)
        self.object.asset = self.asset
        self.object.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        id = request.GET.get("pk", None)
        if id:
            self.asset = AssetModel.objects.get(id=id)
        else:
            self.asset = AssetModel.objects.latest("id")
        return super().post(request, *args, **kwargs)

    # def get_context_data(self, **kwargs):
    #     print(super().get_context_data(**kwargs))
    #     print("kwargs", kwargs)
    #     asset = AssetModel.objects.latest("id")
    #     print(asset)
    #     content = super().get_context_data(**kwargs)
    #     content["form"].initial["asset"] = asset
    #     # content["form"].fields["asset"].disabled = True
    #     print(content["form"].fields["asset"])
    #     return content

    def get_success_url(self):
        return reverse("assetmgt:assetlist")


class AccessoryUpdateView(UpdateView):
    model = Accessories
    template_name = "assetmgt/updateaccessory.html"
    form = AccessoryForm


class AccessoryDeleteView(DeleteView):
    model = Accessories
    success_url = reverse_lazy("assetmgt:assetlist")
    template_name = "assetmgt/deleteaccessory.html"


class AccAsset(ListView):
    model = Accessories
    template_name = "assetmgt/accasset.html"

    def get(self, request, *args, **kwargs):
        id = kwargs.get("pk", None)
        print(id)
        self.object_list = self.get_queryset()
        querys = Accessories.objects.filter(asset=id)
        context = {}
        assetname = AssetModel.objects.get(pk=id)
        context["asset"] = assetname
        context["object_list"] = querys
        print(context)
        return render(request, self.template_name, context)

assetmgt/templates/assetmgt/accasset.html
{%extends '_blank.html'%}   
{%block qux_content%} 
<div class="container">
    <div class="row">
        <div class="col d-flex justify-content-center" style="padding:20px;">
            <div class="card" style="width: 18rem; border:2px solid grey;">
                <div class="card-body">
                    <h5 class="card-title">Asset : {{asset}}</h5>
                    <hr/>
                    <h6>Accessories</h6>
                </div>
                <ul class="list-group list-group-flush">
                {%for obj in object_list%}
                    <li class="list-group-item">* {{obj.accessory_type}}</li>
                {%endfor%}           
                </ul>
            </div>
        </div>
    </div> 
<div>
    
<div class="container">  
    <div class="col d-flex justify-content-center offset-md-5" >
        <div class="col" style="padding:5px;">
            <a href="{%url 'assetmgt:assetlist' %}" class="btn btn-secondary" style="padding:10px;">OK</a>
        <div>
    </div> 
</div>   

{%endblock%}

assetmgt/templates/assetmgt/accessory_detail.html
{%extends '_blank.html'%}   
{%block qux_content%} 
{%block carddata%}
<div class="container offset-md-5">
    <h5 style="padding:10px;">Accessory Detail</h5>
</div>
<div class="container">
    <div class="row">
        <div class="col d-flex justify-content-center" style="padding:20px;">
            <div class="card" style="width: 18rem; border:2px solid grey;">
                <div class="card-body">
                    <h5 class="card-title">Accessory: {{object.id}} {{object.type}}</h5>
                </div>
                <ul class="list-group list-group-flush">
                <li class="list-group-item">Model ID: {{object.model_id}}</li>
                <li class="list-group-item">Type: {{object.accessory_type}}</li>
                <li class="list-group-item">Asset: {{object.asset}}</li>
                </li>
                </ul>
            </div>
        </div>
    </div> 
<div>
{%endblock carddata%}  

{%if request.user.is_superuser%}    
<div class="container">  
    <div class="col d-flex justify-content-center offset-md-5" >
        <div class="col" style="padding:5px;">
            <a href="{%url 'assetmgt:acc_update' object.id%}" class="btn btn-secondary" style="padding:10px;">Update</a>
            <a href="{%url 'assetmgt:acc_delete' object.id %}" class="btn btn-secondary"style="padding:10px; margin:10px;">Delete</a>
        <div>
    </div> 
</div>
{%endif%}   

{%endblock%}

assetmgt/templates/assetmgt/addaccessory.html
{%extends '_blank.html'%}
{%block qux_content%}
<div class="d-flex justify-content-center" style="margin:20px;">
    {% comment %} Card {% endcomment %}
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">Add Accessory</h5>
        </div>
        <div class="card-body">
            <form action='' method = 'POST'>
                {% csrf_token %}
                    <table class="table">
                        {{form.as_table}}
                    </table>
                <div class="d-flex justify-content-around">
                    {% comment %} <button type='submit' name="save_add" class="btn btn-secondary btn-sm" >Save & Add</button> {% endcomment %}
                    <button type='submit' name="add" class="btn btn-secondary btn-sm">Save</button>
                    <a href="{%url 'assetmgt:assetlist'%}" class="btn btn-secondary btn-sm">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

assetmgt/templates/assetmgt/addasset.html
{%extends '_blank.html'%}

{%block qux_content%}
<div class="d-flex justify-content-center" style="margin:20px;">
    {% comment %} Card {% endcomment %}
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">Add Asset</h5>
        </div>
        <div class="card-body">
            <form action='' method = 'POST'>
                {% csrf_token %}
                    <table class="table">
                        {{assetform.as_table}}
                    </table>
                <div class="d-flex justify-content-between">
                    <button type='submit' name="save_add" class="btn btn-secondary btn-sm" >Save & Add</button>
                    <button type='submit' name="add" class="btn btn-secondary btn-sm">Save</button>
                    <button type='submit' name="acc_add" class="btn btn-secondary btn-sm">Add Accessories</button>
                    <a href="{%url 'assetmgt:assetlist'%}" class="btn btn-secondary btn-sm">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}


























{% comment %} change2 {% endcomment %}
{% comment %} <div class="container">
    <div class="row">
    <div class="col d-flex justify-content-center">
        <h5 style="padding:10px;">Add Asset</h5>
    </div>
    <div class="col d-flex justify-content-center">
        <h5 style="padding:10px;">Add Acessory</h5>
    </div>
    </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                <form action='' method = 'POST'>
                    {% csrf_token %}
                        <table class="table" style="border:1px solid black; border-radius:5px;">
                            {{assetform.as_table}}
                        </table>
                    <div class="d-flex justify-content-center">
                        <button type='submit' name="save_add" class="btn btn-secondary" style="margin-right: 30px; margin-left:20px;">Save & Add</button>
                        <button type='submit' name="add" class="btn btn-secondary" style="margin-right: 30px; margin-left:20px;">Save</button>
                        <a href="{%url 'assetmgt:assetlist'%}" class="btn btn-secondary"style="margin-right: 30px; margin-left:20px;">Cancel</a>
                        <a href="{%url 'assetmgt:acc_add'%}" class="btn btn-secondary">Add Accessories</a>   
                    </div>
                </form>
            </div>
            <div class="col d-flex justify-content-center">
                <div >
                </div>
            </div>
        </div>
</div> {% endcomment %}







{% comment %} change1 {% endcomment %}
{% comment %} <div class="container offset-md-5">
    <h5 style="padding:10px;">Add Asset</h5>
</div>
<div class= >
<form action='' method = 'POST'>
    {% csrf_token %}
    
        <table class="table ">
            {{form.as_table}}
        </table>
    <div class="container offset-md-4">
        <button type='submit' name="save_add" class="btn btn-secondary" style="margin-right: 30px; margin-left:80px;">Save & Add</button>
        <button type='submit' name="add" class="btn btn-secondary" style="margin-right: 30px; margin-left:80px;">Save</button>
        <a href="{%url 'assetmgt:assetlist'%}" class="btn btn-secondary">Cancel</a>   
    </div>
</form>
</div> {% endcomment %}

assetmgt/templates/assetmgt/all_accessories.html
{%extends '_blank.html'%}
{%block qux_content%}

<div>
    <h3 style="text-align:center; padding:20px;">Accessories Available</h3>
</div>

<div class="container">
    <div class="row">
      <div class="col d-flex justify-content-center">
        <table class="table table-hover table-borderless table-md table-listview" style="border:1px solid grey; border-radius: 10px;margin-left:auto;margin-right:auto;">
            <tr style="background-color:#b4b4b4;">
                <th>ID</th>
                <th>Model ID</th>
                <th>Type</th>
                <th>Asset</th>
                <th></th>
                <th></th>
            </tr>
            {%for obj in accessories_list%}
            <tr onclick="showdetails({{obj.id}});">
                <td>{{obj.id}}</td>
                <td>{{obj.model_id}}</td>
                <td>{{obj.accessory_type}}</td>
                <td>{{obj.asset}}</td>
                <td><a href="{%url 'assetmgt:acc_update' obj.id%}" class="btn btn-secondary">Update</a></td>
                <td><a href="{%url 'assetmgt:acc_delete' obj.id%}" class="btn btn-secondary">Delete</a></td>
            </tr>
            {%empty%}
                <p>No Data</p>
            {%endfor%}
        </table>        
      </div>
    </div>
  </div>
{%endblock%}


{% block customjs %}
{{ block.super }}

<script>
    function showdetails(id){
        console.log(id)
        window.location.replace(window.location.origin +"/assetmgt/accessories/detail/"+id)
    }

    function display(){
        var x = document.getElementById('type').value;
        var y = (window.location.origin +"/assetmgt/assets/?type="+x)
        console.log(y)
        window.location.replace(y)
    
    }
</script>

{% endblock %}
   

assetmgt/templates/assetmgt/all_assets.html
{%extends '_blank.html'%}
{%block qux_content%}
<div>
    <h3 style="text-align:center; padding:20px;">Assets Available</h3>
</div>

<div class="container" style="text-align:center; padding:20px;">
    <div class="row">
      <div class="col">
        <select id="type" onchange = "display();" style="float:left; padding:5px;border-radius:5px;">
            <option value="Select">Select Type</option>
            <option value="All">All</option>
            {%for val in assettype%}
            <option value={{val}}>{{val}}</option>
            {% endfor %}
        </select>  
        
        <a href="{%url 'assetmgt:add' %}" class="btn btn-secondary btn-md" style="float:right;">Add Asset</a>
      </div>
    </div>
  </div>

<div class="container">
    <div class="row">
        <table class="table table-hover table-borderless table-md table-listview" style="border:1px solid grey; border-radius: 10px;margin-left:auto;margin-right:auto;">
            <tr style="background-color:#b4b4b4;">
                <th>ID</th>
                <th>Model ID</th>
                <th>Brand</th>
                <th>Type</th>
                <th>Date Procured</th>
                <th>Price</th>
                <th>User</th>
                <th>Date Allotted</th>
                {% if user.is_superuser %}
                <th></th>
                <th></th>
                {%endif%}
            </tr>
            {%for obj in assetmodel_list%}
            <tr onclick="showdetails({{obj.id}});">
                <td>{{obj.id}}</td>
                <td>{{obj.model_id}}</td>
                <td>{{obj.brand_name}}</td>
                <td>{{obj.type_of_asset}}</td>
                <td>{{obj.date_procured}}</td>
                <td style="text-align:right;">{{obj.price}}</td>
                <td>{{obj.user}}</td>
                <td>{{obj.date_allotted}}</td>
                {% if user.is_superuser %}
                <td><a href="{%url 'assetmgt:update' obj.id%}" class="btn btn-secondary">Update</a></td>
                <td><a href="{%url 'assetmgt:delete' obj.id%}" class="btn btn-secondary">Delete</a></td>
                {%endif%}
            </tr>
            {%empty%}
                <p>No Data</p>
            {%endfor%}
        </table>        
    </div>
  </div>
{%endblock%}


{% block customjs %}
{{ block.super }}

<script>
    function showdetails(id){
        console.log(id)
        window.location.replace(window.location.origin +"/assetmgt/"+id)
    }

    function display(){
        var x = document.getElementById('type').value;
        var y = (window.location.origin +"/assetmgt/assets/?type="+x)
        console.log(y)
        window.location.replace(y)
    
    }
</script>

{% endblock %}
   

assetmgt/templates/assetmgt/all_users.html
{%extends '_blank.html'%}   
{%block qux_content%} 
        {%for obj in object_list%}
        <p>{{obj}}</p>
        {%empty%}
        <p>No data</p>
        {% endfor %}
{%endblock%}
        
   

assetmgt/templates/assetmgt/asset_detail.html
{%extends '_blank.html'%}   
{%block qux_content%}
    {%block details%}
    <div class="container">
        {% comment %} <div class="row">
            <h5 class="col d-flex justify-content-center" style="padding:10px; padding-left:50px;">Asset Detail</h5>
            <h5 class="col d-flex justify-content-center" style="padding:10px; padding-left:50px;">Accessories</h5> 
        </div> {% endcomment %}
        <div class="row" style="margin:20px;">
            <div class="col d-flex justify-content-center">
                <div class="card" style="width: 30rem;">
                    <div class="card-body">
                        <h5 class="card-title">Asset {{object.id}}</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Model ID: {{object.model_id}}</li>
                            <li class="list-group-item">Brand: {{object.brand_name}}</li>
                            <li class="list-group-item">Asset Type: {{object.type_of_asset}}</li>
                            <li class="list-group-item">Date Procured: {{object.date_procured}}</li>
                            <li class="list-group-item">Price: {{object.price}}</li>
                            <li class="list-group-item">User: {{object.user}}</li>
                            <li class="list-group-item">Date Allotted: {{object.date_allotted}}</li>
                        </ul>  
                    </div>
                </div>
            </div>
            <div class="col d-flex justify-content-center">
                <div class="card" style="width: 30rem;">
                    <div class="card-body">
                        <h5 class="card-title">Accessories</h5>
                    </div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            {%for obj in acc_list%}
                                <li class="list-group-item">{{obj.accessory_type}}</li>
                            {%endfor%}   
                        </ul>  
                    </div>
                </div>
            </div>
        </div>
    </div>
    {%endblock%}

        <div class="row d-flex justify-content-center" style="margin:20px;">
            <a href="{%url 'assetmgt:assetlist' %}" class="btn btn-secondary" style="padding:10px;">Back</a>
        </div>
    
    
{%endblock%}


{% comment %} 
<div class="card" style="width: 18rem; border:2px solid grey;">
                <div class="card-body">
                    <h5 class="card-title">Asset : {{asset}}</h5>
                    <hr/>
                    <h6>Accessories</h6>
                </div>
                <ul class="list-group list-group-flush">
                {%for obj in object_list%}
                    <li class="list-group-item">* {{obj.accessory_type}}</li>
                {%endfor%}           
                </ul>
            </div>
 {% endcomment %}


{% comment %} prev code {% endcomment %}
{% comment %} <div class="row" >
    <h5 class="col d-flex justify-content-center" style="padding:10px; padding-left:50px;">Asset Detail</h5>
    <h5 class="col d-flex justify-content-center" style="padding:10px; padding-left:50px;">Accessories</h5>
    </div>

    <div class="container">
        <div class="row">
          <div class="col d-flex justify-content-center">
            <h5>Asset Detail</h5>
            <div class="card" style="width: 25rem; border:2px solid grey;">
                <div class="card-body">
                    <h5 class="card-title">Asset: {{object.id}}</h5>
                </div>
                <ul class="list-group list-group-flush">
                <li class="list-group-item">Model ID: {{object.model_id}}</li>
                <li class="list-group-item">Brand: {{object.brand_name}}</li>
                <li class="list-group-item">Asset Type: {{object.type_of_asset}}</li>
                <li class="list-group-item">Date Procured: {{object.date_procured}}</li>
                <li class="list-group-item">Price: {{object.price}}</li>
                <li class="list-group-item">User: {{object.user}}</li>
                <li class="list-group-item">Date Allotted: {{object.date_allotted}}</li>
                </ul>
            </div>
          </div>
          <div class="col d-flex justify-content-center">
            <h5>Accessories</p>
          </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="col d-flex justify-content-center">
            <p>hello</p>
          </div>
          <div class="col d-flex justify-content-center">
            2 of 2
          </div>
        </div>
    </div>


    <div class="row" style="margin-top:20px;">
    <div class="container offset-md-5 col d-flex justify-content-center" style="margin-left:auto; margin-right:auto;">  
                <a href="{%url 'assetmgt:assetlist' %}" class="btn btn-secondary" style="padding:10px;">Back</a>
    </div>
    </div>


</div> {% endcomment %}




{% comment %} <div class="row">
    <div class="col d-flex justify-content-center" style="padding:10px; padding-left:50px;">
        {%block cardassetdata%}
        <div class="container">
            <div class="row">
                <div class="col d-flex justify-content-center" style="padding:20px;">
                    <div class="card" style="width: 30rem; border:2px solid grey;">
                        <div class="card-body">
                            <h5 class="card-title">Asset: {{object.id}}</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                        <li class="list-group-item">Model ID: {{object.model_id}}</li>
                        <li class="list-group-item">Brand: {{object.brand_name}}</li>
                        <li class="list-group-item">Asset Type: {{object.type_of_asset}}</li>
                        <li class="list-group-item">Date Procured: {{object.date_procured}}</li>
                        <li class="list-group-item">Price: {{object.price}}</li>
                        <li class="list-group-item">User: {{object.user}}</li>
                        <li class="list-group-item">Date Allotted: {{object.date_allotted}}</li>
                        </ul>
                    </div>
                </div>
            </div> 
        <div>
        {%endblock cardassetdata%}
    </div> 
    <div class="col d-flex justify-content-center" style="padding:10px; padding-left:50px;">
        {%block cardaccdata%}
        <div class="container">
            <div class="row">
                <div class="col d-flex justify-content-center" style="padding:20px;">
                    <div class="card" style="width: 18rem; border:2px solid grey;">
                        <div class="card-body">
                            <h5 class="card-title">Accessory: {{object.id}} {{object.type}}</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                        <li class="list-group-item">Model ID: {{object.model_id}}</li>
                        <li class="list-group-item">Type: {{object.accessory_type}}</li>
                        <li class="list-group-item">Asset: {{object.asset}}</li>
                        </li>
                        </ul>
                    </div>
                </div>
            </div> 
        <div>
        {%endblock cardaccdata%}
    </div>  
    </div>

 {% endcomment %}

assetmgt/templates/assetmgt/updateasset.html
{%extends '_blank.html'%}   
{%block qux_content%} 
<div class="container">
    <div class="row">
        <div class="col d-flex justify-content-center" style="margin:20px;">
            {% comment %} Card {% endcomment %}
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <h5 class="card-title">Edit Asset</h5>
                </div>
                <div class="card-body">
                    <form action='' method = 'POST'>
                        {% csrf_token %}
                            <table class="table">
                                {{form.as_table}}
                            </table>
                        <div class="d-flex justify-content-around">
                            <button type='submit'class="btn btn-secondary">Update</button>
                            <a href="{%url 'assetmgt:assetlist'%}" class="btn btn-secondary">Cancel</a> 
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col d-flex justify-content-center" style="margin:20px;">
            <div class="card" style="width: 30rem;">
                <div class="card-body">
                    <h5 class="card-title">Accessories</h5>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        {%for obj in acc_list%}
                            <li class="list-group-item">{{obj.accessory_type}}</li>
                        {%endfor%}   
                    </ul>  
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-around">
                        <a href="{%url 'assetmgt:acc_add'%}?pk={{id}}" class="btn btn-secondary btn-md">Add Accessory</a>
                        <a href="{%url 'assetmgt:accessorylist'%}?pk={{id}}" class="btn btn-secondary btn-md">Delete Accessory</a> 
                    </div>
                </div>
            </div>
        </div>
    </div>  
</div>
{%endblock%}